[functions]
  included_files = [
    "lib/tesseract-worker.cjs",
    "node_modules/tesseract.js/src/worker-script/**",
    "node_modules/tesseract.js-core/**",
    "eng.traineddata",
    "vie.traineddata"
  ]
